stages:          # List of stages for jobs, and their order of execution
  - install_tools
  - test
  - security
  - build
  - docker
  - docker_image_scan

install_mvn_trivy_docker_kubectl:       # This job runs in the tool install stage, which runs first.
  stage: install_tools
  script:
    - sudo apt install -y openjdk-17-jre-headless
    - sudo apt install -y maven
    - sudo apt install -y docker.io && sudo chmod 666 /var/run/docker.sock
    - sudo apt-get install -y wget apt-transport-https gnupg lsb-release
    - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
    - echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
    - sudo apt-get update
    - sudo apt-get install -y trivy
    - sudo snap install kubectl --classic
    - echo "installed tools..."

  tags:
    - self-hosted

unit_testing:       # This job runs in the testing stage.
  stage: test
  script:
    - mvn test
  tags:
    - self-hosted

trivy_fs_scan:       # This job runs in the security stage.
  stage: security
  script:
    - trivy fs --format table -o fs.html .
  tags:
    - self-hosted

sonarqube-check:
  stage: security
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
  only:
    - main

aws-configure:
  stage: docker
  image: amazon/aws-cli:latest
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  script:
    - echo "Verifying AWS CLI Configuration"
    - aws s3 ls # Test AWS command




build_tag_push_image:       # This job runs in the docker stage
  stage: docker
  script:
    - mvn package
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767397755297.dkr.ecr.us-east-1.amazonaws.com
    - docker build -t java .
    - docker tag java:latest 767397755297.dkr.ecr.us-east-1.amazonaws.com/java:latest
    - docker push 767397755297.dkr.ecr.us-east-1.amazonaws.com/java:latest
  only:
    - main
  tags:
    - self-hosted

docker_scan:
  stage: docker_image_scan
  script:
    - trivy image --format table --output trivy-report.html haroonf8/javaapp:latest
  artifacts:
    paths:
      - trivy-report.html
    expire_in: 1 hour
  tags:
    - self-hosted



